//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_RadialMenu : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 RadialPosition
        {
            get
            {
                return SteamVR_Actions.radialMenu_RadialPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean CloseRadial
        {
            get
            {
                return SteamVR_Actions.radialMenu_CloseRadial;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectOption
        {
            get
            {
                return SteamVR_Actions.radialMenu_SelectOption;
            }
        }
    }
}
