//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VR_Game : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabAction
        {
            get
            {
                return SteamVR_Actions.vR_Game_GrabAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean WieldedObjectInteract
        {
            get
            {
                return SteamVR_Actions.vR_Game_WieldedObjectInteract;
            }
        }
    }
}
